### ISSUE TITLE
`prefers-reduced-motion` messes up the parser

### ISSUE THREAD

**Issue by argyleink** [flackr/scroll-timeline#100]

**Comment by KhaledPendleton** [comment]
Has a solution been found for this? Ive encountered this problem today. When using `prefers-reduced-motion: no-preference` animations run immediately, not on scroll.

**Comment by manuelmeister** [comment]
@flackr how could this be solved? Can I help with a PR/research?

**Comment by webaware** [comment]
As a work-around: don't wrap the animations in a media query, just turn them off for prefers-reduced-motion: reduce.

```css
@media (prefers-reduced-motion : reduce) {

	.my-scroll-animated-elements {
		transform: none;
		animation: none;
	}

}
```
