### ISSUE TITLE
Have the parser play nice with nested CSS

### ISSUE THREAD

**Issue by bramus** [flackr/scroll-timeline#133]
This does not work in a browser that supports CSS Nesting but no Scroll-Driven Animations:

```css
body {
  div {
    animation: move linear;
    animation-timeline: scroll();
  }
}
```

When removing the nesting, the polyfill works fine.

Demo: https://codepen.io/bramus/pen/XWoWejQ/64471303f33661702c983e3b4b73a83a
