### ISSUE TITLE
Is animation-range for scroll-timeline not supported?

### ISSUE THREAD

**Issue by zaceno** [flackr/scroll-timeline#151]
I have tried using both JS and CSS methods but cannot get `rangeStart:`, `rangeEnd` or `animation-range` to work in Safari or Firefox (where this polyfill would be needed).

For a reproduction, I cloned the repo, ran `npm i`, then edited `demo/basic/anonymous-scroll-timeline.html` to add:

```css
...
 #box_one {
    width: 100px;
    height: 100px;
    background-color: green;
    animation: move linear;
    animation-timeline: scroll(y nearest);
    animation-range: 40px 150px;  /* <--- ADDED THIS LINE */
  }
...
```

In Chrome, this had the intended effect (att first, scrolling does not animate anything, then the box suddenly moves swiftly downward and right). In Safari and Firefox the behaviour is the same as before adding that line. 

If the lack of support for animation-range is intentional, could you suggest a workaround? (For context, what I'm hoping to achieve is a fixed-position large, heroic header, which shrinks down to a small top-bar as one scrolls further down the page.)
