### ISSUE TITLE
I can't get the polyfill to work

### ISSUE THREAD

**Issue by raphaelgoetter** [flackr/scroll-timeline#163]
Hello,

I designed a scroll-timeline animation to create horizontal scroll indicators on a list of tabs.

Here's the result : https://codepen.io/raphaelgoetter/pen/vYvMaOZ

<img width="382" alt="image" src="https://github.com/flackr/scroll-timeline/assets/491029/dbd9f8bc-9e87-41f2-98fe-cd68dddb1d4d">

Code is working fine on Chrome, but I don't understand what's preventing the polyfill from working on Firefox or Safari.

```css
@supports (animation-timeline: view()) {
  .nav-tabs {
    &::after {
      content: "";
      position: sticky;
      right: 0;
      flex-shrink: 0;
      align-self: stretch;
      animation: fade-right linear both;
      animation-timeline: scroll(nearest inline);
      animation-range: 0 50px;
      transform-origin: right;
      background-image: linear-gradient(
        to right,
        transparent,
        rgba(255, 255, 255, 0.5) 50%,
        #fff 80%
      );
    }
  }
}
@keyframes fade-right {
  from {
    width: 100px;
    scale: 1 1;
  }
  to {
    scale: 0 1;
  }
}
```

Did I do something wrong?
