### ISSUE TITLE
animation-timeline: view(); not working in Astro

### ISSUE THREAD

**Issue by preetamslot** [flackr/scroll-timeline#283]
I have this css (inline)

```css
 .content-grid > div {
    animation: up linear both;
    animation-timeline: view();
    animation-range: 0vh 20vh;
  }
  .fade-up {
    animation: up linear both;
    animation-timeline: view();
    animation-range: 0px 200px;
  }

```

It looks like css animations are not triggered (Firefox), only JS animations are working for me.

If someone has a tip, let me know!

https://uinc.netlify.app/ (Project)
