### ISSUE TITLE
The CSS parser accesses code parts that should not be accessed

### ISSUE THREAD

**Issue by bramus** [flackr/scroll-timeline#75]
See https://codepen.io/bramus/pen/MWGozRq/146cdcc8b5b24389d70ac9066d80dcd9?editors=0110 _(which is a fork of https://flackr.github.io/scroll-timeline/demo/view-timeline-css/)_

The animation in that demo will run during the `enter` phase, even though that line of code has been commented out.

```css
#box {
	animation: linear 2s reveal forwards;
	animation-timeline: reveal-image;
/* 	animation-time-range: enter 0% 100%; */
}
```

Same thing happens if you create a Custom Property that has the same name as the property:

```css
#box {
	animation: linear 2s reveal forwards;
	animation-timeline: reveal-image;
 	--animation-time-range: enter 0% 100%;
}
```

Actual Result: The animation runs during the `enter` phase
Expected Result: The animation to run during default range, which is `cover`
