### ISSUE TITLE
Polyfill does not play nice with @layer

### ISSUE THREAD

**Issue by bramus** [flackr/scroll-timeline#80]
When using some of the props inside `@layer` …

```css
@layer foo {
	@supports (animation-timeline: scroll()) {
		/* Hide Warning */
		.warning {
			display: none;
		}
	}
}
```

… it throws this:

```
Uncaught DOMException: Failed to execute 'matches' on 'Element': '@layer foo' is not a valid selector.
    at t.getAnimationTimelineOptions (https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js:1:25932)
    at https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js:1:32971
    at https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js:1:33181
    at Array.forEach (<anonymous>)
    at https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js:1:32922
```

When not using a `@layer`, it works fine.

```css
@supports (animation-timeline: scroll()) {
	/* Hide Warning */
	.warning {
		display: none;
	}
}
```

**Comment by bramus** [comment]
It’s not related to the `@supports` rule BTW. This also throws:

```css
@layer foo {
	.revealing-image {
		view-timeline-name: revealing-image;
		view-timeline-axis: block;

		animation: linear reveal both;
		animation-timeline: revealing-image;

		/* Needed for polyfill (wrong syntax): */
		animation-time-range: enter 25% 100%;

		/* Needed for Chrome Canary: */
		animation-range: enter 25% 100%;
		animation-delay-start: enter 25%;
		animation-delay-end: enter 100%;
	}
}
```
