### ISSUE TITLE
CSS View Timelines are shared?

### ISSUE THREAD

**Issue by bramus** [flackr/scroll-timeline#82]
I’ve [created a CoverFlow demo](https://codepen.io/bramus/pen/MWVExQg?editors=1010) which approaches the problem using the JS side of things. Each `<li>` is linked to a `ViewTimeline`, and during its `contain` phase animations are running. This works fine.

https://user-images.githubusercontent.com/213073/193609107-7480d07d-42d8-4103-aaf5-06584c53d6b7.mp4

When trying to build [a CSS version of it](https://codepen.io/bramus/pen/GRdGoKy/eb996da60fd733dab962105bbe8d0bee), it doesn’t seem to work: all animations on all `<li>` elements only run when the very last `<li>` of the bunch comes into view. It looks like the timeline is shared between all instances, whereas it is expected for each `<li>` to have their own instance attached.

https://user-images.githubusercontent.com/213073/193609185-8713aeea-0be0-4660-8c0d-aa50322411d1.mp4

Used Code:

```css
.cards li {
	view-timeline-name: li-in-and-out-of-view;
	view-timeline-axis: inline;

	animation: 1s linear adjust-z-index;
	animation-timeline: li-in-and-out-of-view;
	animation-time-range: contain 0% 100%;
}

.cards li > img {
	animation: 1s linear rotate-cover;
	animation-timeline: li-in-and-out-of-view;
	animation-time-range: contain 0% 100%;
}
```

_(Used property names follow those the current version of the polyfill supports, not of the latest spec)_
